#!/usr/bin/python3

import sys


def factorize_number(n):
    factors = []
    for i in range(2, n // 2 + 1):
        if n % i == 0:
            factors.append((i, n // i))
            break
    return factors


def factorize_file(input_file):
    with open(input_file, 'r') as file:
        numbers = file.read().splitlines()

    for number in numbers:
        n = int(number)
        factorizations = factorize_number(n)
        for factors in factorizations:
            print(f'{n}={factors[1]}*{factors[0]}')

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    input_file = sys.argv[1]

    factorize_file(input_file)

